var Logger = BetterLog.useSpreadsheet();

var VERSION = "13-ALPHA";
var HOME_PAGE = "https://github.com/baerrach/myth-weaver-utils-google-sheets";

function generatedBy() {
  var s = [];
  s.push("generated by [url=");
  s.push(HOME_PAGE);
  s.push("]Dossier Dominator Statblock Generator[/url]");
  s.push(" v" + VERSION);
  s.push(" on ");
  s.push(new Date().toISOString().slice(0, 10));

  return s.join("");
}
